# Generated by Django 5.0.6 on 2024-07-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_delete_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
